GET http://localhost:8080/login/validateHomerId?userId=1234
Accept: */*
Cache-Control: no-cache

###

POST http://localhost:8080/login/sendSmsCode
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "userId": "1234",
  "phoneNumber": "13012344321"
}

###

