GET http://localhost:8080/login/user/1234
Accept: */*
Cache-Control: no-cache

###

POST http://localhost:8080/login/sms
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "userId": "1234",
  "phoneNumber": "13012344321"
}

###

POST http://localhost:8080/login/session
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "userId": "1234",
  "smsCode": "4563"
}

###

