# mybatis information
mybatis:
  type-aliases-package: com.kuang.login.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.kuang.login.repository: debug
# server information
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/sales_network?characterEncoding=utf-8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379